
package gui;

import parqueogeneral.GestionarParqueo;

/**
 *
 * @author fernandafajardo
 */
public class BienvenidoScreen extends javax.swing.JFrame {

//    private GestionarParqueo gestionarParqueo = new GestionarParqueo();
    
    public BienvenidoScreen() {
        initComponents();
    }
    //Nombre del usuario mostrado en la pantalla
    public void setNombreUsuario(String nombre){
        txtUsuario.setText(nombre);
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBienvenida = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtHorarios = new javax.swing.JLabel();
        comboBoxDias = new javax.swing.JComboBox<>();
        txtCapDisponible = new javax.swing.JLabel();
        iconParking = new javax.swing.JLabel();
        txtRegulares = new javax.swing.JLabel();
        txtEspacioG = new javax.swing.JLabel();
        iconTechado = new javax.swing.JLabel();
        txtTechado = new javax.swing.JLabel();
        txtEspacioT = new javax.swing.JLabel();
        iconDiscapacitado = new javax.swing.JLabel();
        txtDiscapacitados = new javax.swing.JLabel();
        txtEspacioD = new javax.swing.JLabel();
        iconCargaElectrica = new javax.swing.JLabel();
        txtCE = new javax.swing.JLabel();
        txtEspacioCE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantEspacio = new javax.swing.JLabel();
        boxCantidadEspacio = new javax.swing.JTextField();
        txtTipoEspacio = new javax.swing.JLabel();
        boxTipoEspacio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtID = new javax.swing.JLabel();
        boxID = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 51, 140));

        txtBienvenida.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setText("Bienvenid@");

        txtUsuario.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));

        txtHorarios.setForeground(new java.awt.Color(255, 255, 255));
        txtHorarios.setText("Horario de atención día");

        comboBoxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));
        comboBoxDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDiasActionPerformed(evt);
            }
        });

        txtCapDisponible.setForeground(new java.awt.Color(255, 255, 255));
        txtCapDisponible.setText("Capacidad disponible:");

        iconParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signage.png"))); // NOI18N

        txtRegulares.setForeground(new java.awt.Color(255, 255, 255));
        txtRegulares.setText("1. General");

        txtEspacioG.setForeground(new java.awt.Color(255, 218, 0));

        iconTechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/parking-area.png"))); // NOI18N

        txtTechado.setForeground(new java.awt.Color(255, 255, 255));
        txtTechado.setText("2. Techado");

        txtEspacioT.setForeground(new java.awt.Color(255, 218, 0));

        iconDiscapacitado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disabled.png"))); // NOI18N

        txtDiscapacitados.setForeground(new java.awt.Color(255, 255, 255));
        txtDiscapacitados.setText("3. Discapacitado");

        txtEspacioD.setForeground(new java.awt.Color(255, 218, 0));

        iconCargaElectrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/electric-vehicle.png"))); // NOI18N

        txtCE.setForeground(new java.awt.Color(255, 255, 255));
        txtCE.setText("4. Carga Electrica");

        txtEspacioCE.setForeground(new java.awt.Color(255, 218, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reserva su espacio");

        txtCantEspacio.setForeground(new java.awt.Color(255, 255, 255));
        txtCantEspacio.setText("Cantidad de espacios");

        txtTipoEspacio.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoEspacio.setText("Tipo de espacio");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("ID");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHorarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(txtCantEspacio)
                            .addComponent(txtTipoEspacio)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boxTipoEspacio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(boxCantidadEspacio, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iconDiscapacitado)
                                    .addComponent(txtDiscapacitados)
                                    .addComponent(txtRegulares)
                                    .addComponent(iconParking)
                                    .addComponent(txtEspacioG)
                                    .addComponent(txtEspacioD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iconTechado)
                                    .addComponent(txtTechado)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iconCargaElectrica)
                                            .addComponent(txtCE)
                                            .addComponent(txtEspacioCE)))
                                    .addComponent(txtEspacioT))
                                .addGap(67, 67, 67))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCapDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBienvenida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID)
                            .addComponent(boxID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHorarios)
                            .addComponent(comboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapDisponible)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBienvenida)
                        .addComponent(txtUsuario)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconParking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRegulares))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconTechado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTechado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEspacioG)
                            .addComponent(txtEspacioT))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconCargaElectrica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconDiscapacitado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscapacitados))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantEspacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxCantidadEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipoEspacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspacioD)
                            .addComponent(txtEspacioCE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnEditar))
                        .addContainerGap(224, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void comboBoxDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDiasActionPerformed
        // Obtener el día seleccionado del comboBox (suponiendo que comboBoxDias tiene los días de la semana numerados del 1 al 5)
        int diaSeleccionado = comboBoxDias.getSelectedIndex() + 1;

        GestionarParqueo gestionarParqueo = new GestionarParqueo();

        // Mostrar los espacios disponibles para cada tipo de espacio en los campos de texto correspondientes
        txtEspacioG.setText(String.valueOf(gestionarParqueo.mostrarEspaciosDisponibles(diaSeleccionado, 0)+ " espacios"));
        txtEspacioT.setText(String.valueOf(gestionarParqueo.mostrarEspaciosDisponibles(diaSeleccionado, 1)+ " espacios"));
        txtEspacioD.setText(String.valueOf(gestionarParqueo.mostrarEspaciosDisponibles(diaSeleccionado, 2)+ " espacios"));
        txtEspacioCE.setText(String.valueOf(gestionarParqueo.mostrarEspaciosDisponibles(diaSeleccionado, 3)+ " espacios"));
    }//GEN-LAST:event_comboBoxDiasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxCantidadEspacio;
    private javax.swing.JTextField boxID;
    private javax.swing.JTextField boxTipoEspacio;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> comboBoxDias;
    private javax.swing.JLabel iconCargaElectrica;
    private javax.swing.JLabel iconDiscapacitado;
    private javax.swing.JLabel iconParking;
    private javax.swing.JLabel iconTechado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtBienvenida;
    private javax.swing.JLabel txtCE;
    private javax.swing.JLabel txtCantEspacio;
    private javax.swing.JLabel txtCapDisponible;
    private javax.swing.JLabel txtDiscapacitados;
    private javax.swing.JLabel txtEspacioCE;
    private javax.swing.JLabel txtEspacioD;
    private javax.swing.JLabel txtEspacioG;
    private javax.swing.JLabel txtEspacioT;
    private javax.swing.JLabel txtHorarios;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtRegulares;
    private javax.swing.JLabel txtTechado;
    private javax.swing.JLabel txtTipoEspacio;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
