/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import javax.swing.JOptionPane;
import parqueogeneral.GestionarUsuario;
import parqueogeneral.Usuario;


/**
 *
 * @author fernandafajardo
 */

public class InfoScreen extends javax.swing.JFrame {

    /**
     * Creates new form InfoScreen
     */
    
    private GestionarUsuario gestionarUsuarios;
    public InfoScreen() {
        initComponents();
        gestionarUsuarios = GestionarUsuario.getInstace();
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JLabel();
        textPw = new javax.swing.JLabel();
        boxUsuario = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JButton();
        textInfo = new javax.swing.JLabel();
        boxPw = new javax.swing.JPasswordField();
        btnCrearcuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 51, 140));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hola, bienvenid@");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese sus datos para iniciar sesión en su cuenta  ");

        textUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textUsuario.setText("Usuario");

        textPw.setForeground(new java.awt.Color(255, 255, 255));
        textPw.setText("Contraseña");

        boxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUsuarioActionPerformed(evt);
            }
        });

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        textInfo.setForeground(new java.awt.Color(255, 255, 255));
        textInfo.setText("¿No tienes cuenta? ");

        btnCrearcuenta.setBackground(new java.awt.Color(43, 51, 140));
        btnCrearcuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearcuenta.setText("CREAR CUENTA");
        btnCrearcuenta.setBorderPainted(false);
        btnCrearcuenta.setContentAreaFilled(false);
        btnCrearcuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearcuentaMouseClicked(evt);
            }
        });
        btnCrearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearcuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(textInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrearcuenta))
                            .addComponent(textUsuario)
                            .addComponent(textPw)
                            .addComponent(boxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnAcceder))
                            .addComponent(boxPw, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textUsuario)
                .addGap(7, 7, 7)
                .addComponent(boxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAcceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInfo)
                    .addComponent(btnCrearcuenta))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxUsuarioActionPerformed

    
    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        
        // trim() elimina espacios alrededor del texto
        String usuarioIngresado = boxUsuario.getText().trim();
        String passwordIngresado = new String(boxPw.getPassword()).trim();
        
        // Se usa la instancia de Gestionar Usuario compartida
        GestionarUsuario gestionarUsuarios = GestionarUsuario.getInstace();
        Usuario usuarioAutenticado = gestionarUsuarios.autenticarUsuario(usuarioIngresado, passwordIngresado);
 
        
        if(usuarioAutenticado != null){
            BienvenidoScreen bienvenidoScreen = new BienvenidoScreen();
            bienvenidoScreen.setNombreUsuario(usuarioAutenticado.getNombre()); //nombre del usuario
            bienvenidoScreen.setVisible(true);
            bienvenidoScreen.setLocationRelativeTo(null);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. Por favor, inténtelo de nuevo.");
        }
       
    }//GEN-LAST:event_btnAccederActionPerformed
   

    private void btnCrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearcuentaActionPerformed
        
        formScreen formInicio = new formScreen(true);
        this.dispose();
        formInicio.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnCrearcuentaActionPerformed

    private void btnCrearcuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearcuentaMouseClicked

    }//GEN-LAST:event_btnCrearcuentaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField boxPw;
    private javax.swing.JTextField boxUsuario;
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCrearcuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textInfo;
    private javax.swing.JLabel textPw;
    private javax.swing.JLabel textUsuario;
    // End of variables declaration//GEN-END:variables
}
